### PR TITLE
Fixes for XCode Version 7.0 beta 5 (7A176x)

### PR DESCRIPTION
**Pull request by TeunVR**

### CODE REVIEW

**Comment by pbenkoe** [comment]
this would be great!

**Comment by s-aska** [comment]
:+1:

**Comment by ashleymills** [comment]
Thanks for your pull request. Sorry for being off the radar for a couple of weeks… I'll take a look at this in the next couple of days.

Cheers
Ash

**Comment by uny** [comment]
:+1:

**Comment by ashleymills** [comment]
Thanks for the pull request!
Cheers
Ash

**Comment by TeunVR** [comment]
No problem, thanks for the project :+1:

**Pull request merged**
