### PR TITLE
Fix dealloc race condition

### PR DESCRIPTION
**Pull request by connorpower**
Merging this PR will:
- Fix a crash which occurs due to invalid memory access.

## Crash

image

## Race Condition Causing Crash

Simultaneously:
- Thread X (usually main) deallocs the Reachability.swift object
- Thread Y is already in the process of invoking the `SCNetworkReachabilityCallBack`

The `SCNetworkReachabilityCallBack` attempts to access the now deallocated Swift `Reachability` class by taking the unretained value. This causes a crash.

### Isn't this solved with the current `deinit`?

**No.** While `deinit` calls the `stopNotifier()` function which in turn removes the callbacks (`SCNetworkReachabilitySetCallback(reachabilityRef, nil, nil)`) — this doesn't help if a callback is already in flight.

All CoreFoundation APIs are designed with this possible race condition in mind. For this reason, the API's typically request retain/release callbacks be provided wherever an opaque `info` parameter is being passed:

```swift
init(version: CFIndex,
     info: UnsafeMutableRawPointer?,
     retain: ((UnsafeRawPointer) -> UnsafeRawPointer)?,
     release: ((UnsafeRawPointer) -> Void)?,
     copyDescription: ((UnsafeRawPointer) -> Unmanaged<CFString>)?)
```

### Why has it always worked for me?

It's a question of timing. The current code assumes that the callbacks will be removed in `stopNotifer()` (either by calling `stopNotifer()` directly, or via `deinit`) before the next time `SCNetworkReachability` attempts to invoke the callback.

If this happens as assumed, then the callbacks are removed and the `SCNetworkReachability` object is also deallocated along with the `Reachability` class. Business as usual.

Given that the crash only occurs if a callback is in flight at exactly the same point as `Reachability` is dealloc'ed, it's clear that the overwhelming majority of callbacks never face any issues. The problem is more likely to occur the more often `Reachability` is spun up and down — such as in our large battery of unit tests which started triggering this crash.

## Solution

I've provided the retain/release callbacks as expected by CoreFoundation and introduced a private `ReachabilityWeakifier` class which is responsible for breaking the retain cycle otherwise introduced.

More details can be found in the code comments.

It's possible that this PR fixes some of the vague "Reachability crashed" bugs which seem to have been reported but were lacking in details.

### CODE REVIEW

**Comment by connorpower** [comment]
@ashleymills Any update on this? Let me know if you have questions or feedback.

**Comment by ashleymills** [comment]
Hi @connorpower - thanks for this detailed PR, it looks great, and sorry for the delay in getting round to it. The branch has some conflicts - if you could resolve them, I'll get it merged asap.

Cheers
Ash

**Comment by ashleymills** [comment]
… and could you also please update CHANGELOG.md? Thanks

**Comment by connorpower** [comment]
@ashleymills Done ✔️

**Comment by ashleymills** [comment]
> @ashleymills Done ✔️

Brilliant by you!

**Pull request merged**
