### PR TITLE
Update/swift 5

### PR DESCRIPTION
**Pull request by DanielStormApps**

### CODE REVIEW

**Comment by weakfl** [comment]
`.swift-version` is deprecated since [cocoapods 1.4.0](https://blog.cocoapods.org/CocoaPods-1.4.0/) and should be removed.
Instead a `swift_version` attribute should be added to the podspec...

@ashleymills [v4.3.1](https://github.com/ashleymills/Reachability.swift/releases/tag/v4.3.1) hasn't been pushed to cocoapods yet...

**Comment by ashleymills** [comment]
@DanielStormApps Thanks for the PR. I've updated `podspec` to include `swift_version` per @weakfl comment. 

v4.3.1 has now been pushed

Cheers
Ash

**Comment by DanielStormApps** [comment]
> @DanielStormApps Thanks for the PR. I've updated `podspec` to include `swift_version` per @weakfl comment.
> 
> v4.3.1 has now been pushed to trunk
> 
> Cheers
> Ash

My pleasure.
Thank you for the push 🚀

**Comment by break2k** [comment]
Making this a patch update could break some CI for Podfile using `'~> 4.3.0'`. Maybe keeping this in mind could save some trouble in the future.

Good job. Keep it coming.

**Comment by ashleymills** [comment]
@break2k What would you recommend the version should be a change like this?

**Comment by break2k** [comment]
Our requirements would've been met if it would be a minor release. `4.4.0` as a version would be sufficient.

**Pull request closed without merging**
