### PR TITLE
Reformat license into standard format

### PR DESCRIPTION
**Pull request by gaudecker**
- Replaced license text with the standard [MIT format](https://opensource.org/licenses/MIT).
- Removed "All rights reserved" since it's in conflict with the license text below.

### CODE REVIEW

**Comment by gaudecker** [comment]
Wait a minute, was the license MIT at all? [CocoaPods](https://cocoapods.org/pods/ReachabilitySwift) displays the license as MIT, but the original text looks like a BSD-license. If that is the case, please ignore this PR. :heart:

**Comment by ashleymills** [comment]
Hi - does it matter which licence is in there? Which one is best? I really don't care - so should I go and merge this PR? 

Thanks for your input!
Ash

**Comment by gaudecker** [comment]
It does not matter from the developer's perspective, so choose the one you prefer (although MIT seems to be favoured by the masses), as long as it's consistent with CocoaPods and communicated properly to other developers.

For me the only thing to consider is to include the proper attribution and license when distributing my app.

**Comment by ashleymills** [comment]
Thanks for the PR

Cheers
Ash

**Pull request merged**
