### PR TITLE
Feature/ios10

### PR DESCRIPTION
**Pull request by tomcomer**
Updates for Xcode 8 beta 6 swift changes

### CODE REVIEW

**Comment by LucasTizma** [comment]
Nitpick: Lowercase `ReachabilityError` cases, per the new Swift 3 naming conventions.

**Comment by Tulleb** [comment]
Why didn't you merge it @ashleymills...? I'm using it for almost a month now and it looks fine.

**Comment by ashleymills** [comment]
@Tulleb The latest release supports Swift 3.0 (tag v3.0). There's also a version for Swift 2.3 (tag v2.4)

**Comment by Tulleb** [comment]
Ok great, didn't see the release :)
Thanks a lot @ashleymills!

**Pull request closed without merging**
