### PR TITLE
update podspec to support 5.1.0

### PR DESCRIPTION
**Pull request by askari01**

### CODE REVIEW

**Comment by rockebee** [comment]
Hi  @ashleymills,
we have just seen that the 5.1.0 version is still not available via CocoaPods - would you mind to merge this PR and update the trunk accordingly, so all dependency managers are on the same line?

Many thx in advance!

**Comment by vg-identance** [comment]
Hi @ashleymills any updates on this?

**Comment by laxmorek** [comment]
Im looking forward too :)

**Comment by baottran** [comment]
Just another ping to @ashleymills  for this update

**Review by LowAmmo — APPROVED** [review]

**Review by LowAmmo — APPROVED** [review]

**Comment by LowAmmo** [comment]
@askari01 , @ashleymills  - Any chance we could update this PR for 5.2.0, and get it pulled in and released to cocoapods?

**Comment by askari01** [comment]
@ashleymills @LowAmmo I don't have write access to merge :)

**Comment by alarochelle** [comment]
Yep, +1 on that, seems like the 2 latest releases have been forgotten for Cocoapods. Would it be possible to update the podspec and release it?

**Comment by maurovc** [comment]
+1 as 5.2.0+ includes important manifest changes we need to consume

**Pull request closed without merging**
